### ISSUE TITLE
Parse failure = abort compile step

### ISSUE THREAD

**Issue by devans** [olim7t/sbt-scalariform#2]
The fact that scalariform's ScalaParserExceptions prevent the build action from proceeding to compile has been causing us a lot of problems--notably that it becomes hard to tell where the syntax typo is (it would be more tolerable if the scalariform error messages pointed to file/line). We'd like the formatter to fail quietly on parsing exceptions and let the compiler handle figuring out where the problem is. This seems like it's the correct (general) behavior, is there some reason you ran into not to do it this way? The formatter itself is obviously set up to work when the code is error-free, it's just a little bit more complicated when doing it as a pre-compile step instead.

**Comment by olim7t** [comment]
A formatting error should definitely not prevent compilation, I'll fix that.

When initially writing the plugin, I hesitated whether to format pre- or post-compilation. The problem with post-compilation is that you end up with a source and a class file that are possibly desynchronized, therefore you could get wrong line numbers if a runtime exception occurred.
Therefore I chose pre-compile as the default; note, however, that with the current version of the plugin it is possible to reconfigure the project definition to perform post-compile.

**Comment by devans** [comment]
Yeah, pre-compile is definitely the way to go, just best effort. We were just wondering if there was some reason not to fail quietly we couldn't think of. Thanks for all your help!

**Comment by olim7t** [comment]
Fixed: http://github.com/olim7t/sbt-scalariform/commit/2e46d2c6717796d017cc840445695654382d5eee
