### ISSUE TITLE
sbt-scalariform can’t find the scalariform release in the repo anymore

### ISSUE THREAD

**Issue by Debilski** [olim7t/sbt-scalariform#3]
The scalariform 0.0.5-SNAPSHOT version seems to have been removed from repo-snapshots. Is it possible to get a new version of sbt-scalariform to scala-tools.org soon which fixes that and relies on 0.0.5 or 0.0.6 instead?

**Comment by olim7t** [comment]
Yes, I've been wanting to roll out a new version since the latest versions of scalariform were released. I'll address that this week.

**Comment by Debilski** [comment]
Great.

**Comment by olim7t** [comment]
Fixed in version 1.0.2 (depends on Scalariform 0.0.7).
