### ISSUE TITLE
Add option to disable auto-formatting

### ISSUE THREAD

**Issue by Debilski** [olim7t/sbt-scalariform#4]
Would it be possible to have an option which prevents the automatic formatting of code before every compilation? I don’t want to disable the plugin itself for that but there are a couple of reasons for doing the formatting manually only from time to time.

One reason is that it means less confusion for some text editors but more important is that whenever I make code fixes in a repo which uses a different version of scalariform than the main repo, I get loads of unrelated line changes and need to sort them out before e.g. git pull works.

**Comment by olim7t** [comment]
What you want is to remove the dependency of `compile` on `formatSources`. The problem is that the sbt API does not allow this. As a workaround, you can do this:

```
// Override formatSources so that it does nothing
override lazy val formatSources = Empty
// Expose the original action under a new name
lazy val formatSources2 = formatSourcesAction
```

Then in sbt you run `format-sources2` manually when needed.

I'll include an option in the next release.

**Comment by olim7t** [comment]
Done in 1.0.2 (see the explanations about `formatBeforeCompiling` in readme).

**Comment by Debilski** [comment]
Many thanks. That’s all that was needed.
