### ISSUE TITLE
Scalariform 0.0.9

### ISSUE THREAD

**Issue by LudovicPatey** [olim7t/sbt-scalariform#5]
Hello,
Great plugin !

Could it be possible to make sbt-scalariform independant of scalariform version to be able to get last version of scalariform ?
If no, could you update this plugin ?

Best regards,

**Comment by olim7t** [comment]
Hi Ludovic,

I've published version 1.0.3 of the plugin, which depends on Scalariform 0.0.9. Let me know how it works for you.

**Comment by LudovicPatey** [comment]
The plugin works perfectly. Thanks.
